version: 2
jobs:
  test_client:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          command: |
            docker build -t soundestmammal/portfolio-test -f ./client/Dockerfile.dev ./client
            docker run -e CI=true soundestmammal/portfolio-test npm test
  upload_images:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          command: |
            docker build -t soundestmammal/portfolio ./client
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
            docker push soundestmammal/portfolio
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          command: bash ./scripts/deploy.sh

workflows:
  version: 2
  Portfolio_Workflow:
    jobs:
      - test_client
      - upload_images:
          requires:
            - test_client
      - deploy:
          requires:
            - test_client
            - upload_images
          filters:
            branches:
              only: version3
